name: clang-format check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          exclude: '**/build'
          extensions: 'h,cpp,c,hpp'
          clangFormatVersion: 20